force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer__c</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers__c</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Customer_c__c.field-meta.xml
<CustomField>
    <fullName>Customer_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer__c</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/W6.2/CustomerTriggerHandler.cls
public with sharing class CustomerTriggerHandler {
/*  a. Whenever a new Customer is created, create following default Payment records
- Amount = $0.1, Mode = Online
- Amount = $1, Mode = Crypto */
    
    public static void createDefaultPayments(List<Customer__c> triggerNew){
        
        List<Payment__c> defaultPaymentsList = new List<Payment__c>();
        
        for(Customer__c c : triggerNew){

            Payment__c pCrypto = new Payment__c();
            pCrypto.Mode__c = 'Crypto';
            pCrypto.Customer_c__c = c.id;
            pCrypto.Amount__c = 1;
            defaultPaymentsList.add(pCrypto);

            Payment__c pOnline = new Payment__c();
            pOnline.Mode__c = 'Online';
            pOnline.Customer_c__c = c.id;
            pOnline.Amount__c = 0.1;
            defaultPaymentsList.add(pOnline);
        }
        if(!defaultPaymentsList.isEmpty()){
            Insert defaultPaymentsList;
        }
    }
        /*  b. Whenever Active Customers are deleted, all the corresponding payments should be deleted.
        c. Whenever In Active Customers are deleted, all the corresponding online payment records
        should be deleted.  */
    public static void updateRelatedPayments(List<Customer__c> triggerOld){
        Set<Id> active =new Set<Id>();
        Set<id> inactive=new Set<Id>();
        //Collecting active and inactive account Ids seperately
        for(Customer__c c: triggerOld){
            if(c.active__c ==true){
                active.add(c.id);
            }else{
                inactive.add(c.id);
            }
        }
        //Find all the related payment records of all active Customer records
        if(!active.isEmpty()){
            List<Payment__c> payments1 =[select id FROM Payment__c where Customer_c__c in :active];
            if(!payments1.isEmpty())
                delete payments1;
        }
        //Find all the related 'Online' payment records of all inactive Customer records
        if(!Inactive.isEmpty()){
            List<Payment__c> onlines=[select id FROM Payment__c WHERE Customer_c__c in :inactive and Mode__c='Online'];
            if(!onlines.isEmpty())
                delete onlines;
        }
    }

}